### ISSUE TITLE
IntegrityError: no partition of relation "myapp_mymodel" found for row, when trying to create objects

### ISSUE THREAD

**Issue by tahmidkhan** [chaitin/django-pg-timepart#5]
I set up my partitions, and then applied it to my table as follows:

```
from pg_partitioning.decorators import ListPartitioning

@ListPartitioning(partition_key='collection')
class MyModel(models.Model):
	collection = models.TextField(default='collection')
```

I tried to create an object using the following code:

`MyModel.objects.create(collection='abcd1234')`

I get the following error:

```
django.db.utils.IntegrityError: no partition of relation "myapp_mymodel" found for row
DETAIL:  Partition key of the failing row contains (collection) = (abcd1234).
```

**Comment by virusdefender** [comment]
You should create your partition at first

https://github.com/chaitin/django-pg-timepart/blob/master/tests/tests.py#L129

https://django-pg-partitioning.readthedocs.io/en/latest/api.html#pg_partitioning.manager.ListPartitionManager.create_partition
